version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - utarwyn
  ignore:
  - dependency-name: "@types/node"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - utarwyn
